#!/usr/bin/env bash

# This script is used to factor the modulus of the RSA key pair
# used to sign the challenge file. The modulus is provided as
# a command line argument.

factorize() {
	local n=$1
	local x=2
	while (( x * x <= n)); do
		if (( n % x)); then
			((x++))
		else
			echo "$n=$x*$((n / x))"
			return
		fi
	done
	echo "$n=1*$n"
}

while read -r n; do
	factorize $n
done < "$1"